/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_App */

#ifndef _Included_app_App
#define _Included_app_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_App
 * Method:    showMinVCLWindowUsingJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_App_showMinVCLWindowUsingJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
